/* 奇幻战线单位注册表。这里补齐标准字段、兼容展示字段，并在模块加载时做完整校验。 */

import { UNIT_CONFIGS } from './assets/unitConfigs.ts';
import type {
  FantasyLaneArmorClass,
  FantasyLaneArmorType,
  FantasyLaneCombatRole,
  FantasyLaneDamageProfile,
  FantasyLaneDamageType,
  FantasyLaneFootprint,
  FantasyLaneHeroDefinition,
  FantasyLaneLaneId,
  FantasyLaneLayer,
  FantasyLaneRangeBand,
  FantasyLaneRoleGroup,
  FantasyLaneTacticalSkillDefinition,
  FantasyLaneTargetRule,
  FantasyLaneUnitDefinition,
  FantasyLaneUnitSize,
} from './fantasyLaneTypes.ts';

type UnitSeed = {
  id: keyof typeof UNIT_CONFIGS;
  fallbackName: string;
  shortName: string;
  icon: string;
  layer: FantasyLaneLayer;
  rangeBand: FantasyLaneRangeBand;
  footprint: FantasyLaneFootprint;
  damageProfile: FantasyLaneDamageProfile;
  targetRule: FantasyLaneTargetRule;
  armorType: FantasyLaneArmorType;
  armorClass: FantasyLaneArmorClass;
  role: FantasyLaneCombatRole;
  cost: number;
  cooldownMs: number;
  pop: number;
  maxHp: number;
  armorHp: number;
  damage: number;
  damageType: FantasyLaneDamageType;
  moveSpeed: number;
  acquireRange: number;
  preferredRange: number;
  minimumRange: number;
  attackIntervalMs: number;
  attackWindupMs: number;
  attackAnimMs: number;
  projectileSpeed: number;
  collisionRadius: number;
  splashRadius: number;
  attackColor: string;
  tags: string[];
  summary: string;
  signature: string;
};

const REQUIRED_STANDARD_FIELDS: Array<keyof FantasyLaneUnitDefinition> = [
  'id',
  'name',
  'shortName',
  'cost',
  'pop',
  'maxHp',
  'armorHp',
  'layer',
  'rangeBand',
  'footprint',
  'role',
  'damageType',
  'damageProfile',
  'targetRule',
  'moveSpeed',
  'acquireRange',
  'preferredRange',
  'minimumRange',
  'attackIntervalMs',
  'attackWindupMs',
  'attackAnimMs',
  'projectileSpeed',
  'collisionRadius',
  'splashRadius',
];

const LAYERS: FantasyLaneLayer[] = ['ground', 'air'];
const RANGE_BANDS: FantasyLaneRangeBand[] = ['melee', 'ranged'];
const FOOTPRINTS: FantasyLaneFootprint[] = ['small', 'medium', 'large', 'giant'];
const ROLES: FantasyLaneCombatRole[] = ['tank', 'fighter', 'sniper', 'caster', 'siege', 'air_sup', 'finisher'];
const DAMAGE_TYPES: FantasyLaneDamageType[] = ['physical', 'pierce', 'blast', 'magic', 'siege', 'antiAir'];
const DAMAGE_PROFILES: FantasyLaneDamageProfile[] = ['single', 'aoe'];
const TARGET_RULES: FantasyLaneTargetRule[] = ['ground_only', 'air_only', 'both'];
const ARMOR_TYPES: FantasyLaneArmorType[] = ['light', 'heavy', 'swarm', 'structure', 'air'];

// 从渲染配置兜底读取单位中文名，避免展示层和运行时出现名称偏差。
function resolveUnitName(id: keyof typeof UNIT_CONFIGS, fallbackName: string) {
  return UNIT_CONFIGS[id]?.name ?? fallbackName;
}

// 保留旧 UI 需要的 lane 字段，但从新标准字段里稳定推导出来。
function toLegacyLane(layer: FantasyLaneLayer, role: FantasyLaneCombatRole): FantasyLaneLaneId {
  if (layer === 'air') return 'air';
  if (role === 'tank' || role === 'finisher') return 'front';
  if (role === 'fighter') return 'mid';
  return 'rear';
}

// 保留旧 UI 的 roleGroup，但不再让它成为运行时行为来源。
function toLegacyRoleGroup(role: FantasyLaneCombatRole): FantasyLaneRoleGroup {
  switch (role) {
    case 'tank':
      return 'tank';
    case 'fighter':
      return 'melee';
    case 'sniper':
      return 'ranged';
    case 'caster':
      return 'magic';
    case 'air_sup':
      return 'air';
    default:
      return 'finisher';
  }
}

// 保留旧展示尺寸标签，运行时仍只认 footprint。
function toLegacySize(footprint: FantasyLaneFootprint): FantasyLaneUnitSize {
  switch (footprint) {
    case 'small':
      return 'S';
    case 'medium':
      return 'M';
    case 'large':
      return 'L';
    default:
      return 'XL';
  }
}

// 统一把单位种子扩成完整定义，避免运行时再做默认字段兜底。
function createUnit(seed: UnitSeed): FantasyLaneUnitDefinition {
  const name = resolveUnitName(seed.id, seed.fallbackName);

  return {
    id: seed.id,
    name,
    shortName: seed.shortName,
    cost: seed.cost,
    pop: seed.pop,
    maxHp: seed.maxHp,
    armorHp: seed.armorHp,
    layer: seed.layer,
    rangeBand: seed.rangeBand,
    footprint: seed.footprint,
    role: seed.role,
    damageType: seed.damageType,
    damageProfile: seed.damageProfile,
    targetRule: seed.targetRule,
    moveSpeed: seed.moveSpeed,
    acquireRange: seed.acquireRange,
    preferredRange: seed.preferredRange,
    minimumRange: seed.minimumRange,
    attackIntervalMs: seed.attackIntervalMs,
    attackWindupMs: seed.attackWindupMs,
    attackAnimMs: seed.attackAnimMs,
    projectileSpeed: seed.projectileSpeed,
    collisionRadius: seed.collisionRadius,
    splashRadius: seed.splashRadius,
    damage: seed.damage,
    armorType: seed.armorType,
    icon: seed.icon,
    attackColor: seed.attackColor,
    cooldownMs: seed.cooldownMs,
    armorClass: seed.armorClass,
    roleGroup: toLegacyRoleGroup(seed.role),
    lane: toLegacyLane(seed.layer, seed.role),
    targetClass: seed.armorType,
    size: toLegacySize(seed.footprint),
    attackRange: seed.preferredRange,
    canAttackGround: seed.targetRule !== 'air_only',
    canAttackAir: seed.targetRule !== 'ground_only',
    tags: seed.tags,
    summary: seed.summary,
    signature: seed.signature,
  };
}

const UNIT_SEEDS: UnitSeed[] = [
  {
    id: 'goblin_shield',
    fallbackName: '哥布林盾兵',
    shortName: '盾兵',
    icon: '🛡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'tank',
    cost: 35,
    cooldownMs: 3200,
    pop: 1,
    maxHp: 500,
    armorHp: 120,
    damage: 34,
    damageType: 'physical',
    moveSpeed: 2.8,
    acquireRange: 10,
    preferredRange: 1.2,
    minimumRange: 0,
    attackIntervalMs: 960,
    attackWindupMs: 140,
    attackAnimMs: 240,
    projectileSpeed: 0,
    collisionRadius: 1.2,
    splashRadius: 0,
    attackColor: '#60a5fa',
    tags: ['frontline', 'starter'],
    summary: '低费开路盾兵，负责把第一波团战站住。',
    signature: '低费、前排、短 CD',
  },
  {
    id: 'archer',
    fallbackName: '弓箭手',
    shortName: '弓手',
    icon: '🏹',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'light',
    armorClass: 'light',
    role: 'sniper',
    cost: 42,
    cooldownMs: 3800,
    pop: 1,
    maxHp: 300,
    armorHp: 0,
    damage: 36,
    damageType: 'physical',
    moveSpeed: 1.9,
    acquireRange: 26,
    preferredRange: 19,
    minimumRange: 2.4,
    attackIntervalMs: 820,
    attackWindupMs: 200,
    attackAnimMs: 280,
    projectileSpeed: 30,
    collisionRadius: 1,
    splashRadius: 0,
    attackColor: '#22c55e',
    tags: ['antiAir', 'starter'],
    summary: '低费后排点射位，补对空和清轻甲都很稳。',
    signature: '低费、对空、持续点射',
  },
  {
    id: 'crypt_crawler',
    fallbackName: '墓穴爬兽',
    shortName: '爬兽',
    icon: '🕷',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'swarm',
    armorClass: 'swarm',
    role: 'fighter',
    cost: 48,
    cooldownMs: 3400,
    pop: 1,
    maxHp: 430,
    armorHp: 0,
    damage: 62,
    damageType: 'pierce',
    moveSpeed: 4.6,
    acquireRange: 11,
    preferredRange: 1.1,
    minimumRange: 0,
    attackIntervalMs: 880,
    attackWindupMs: 110,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 0.95,
    splashRadius: 0,
    attackColor: '#7c3aed',
    tags: ['pierce', 'swarm'],
    summary: '小体型切入兵，能顺着缝隙快速扑到后排。',
    signature: '穿插、破甲、快压',
  },
  {
    id: 'bat_swarm',
    fallbackName: '蝠群',
    shortName: '蝠群',
    icon: '🦇',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'swarm',
    role: 'air_sup',
    cost: 52,
    cooldownMs: 3600,
    pop: 1,
    maxHp: 360,
    armorHp: 0,
    damage: 58,
    damageType: 'antiAir',
    moveSpeed: 5.1,
    acquireRange: 14,
    preferredRange: 1.3,
    minimumRange: 0,
    attackIntervalMs: 860,
    attackWindupMs: 120,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 0.95,
    splashRadius: 0,
    attackColor: '#8b5cf6',
    tags: ['antiAir', 'swarm'],
    summary: '低费空军骚扰位，用来抢空域和拖乱阵型。',
    signature: '空军、短 CD、骚扰',
  },
  {
    id: 'flame_warlock',
    fallbackName: '炎术士',
    shortName: '炎术',
    icon: '🔥',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 72,
    cooldownMs: 5500,
    pop: 2,
    maxHp: 360,
    armorHp: 0,
    damage: 64,
    damageType: 'blast',
    moveSpeed: 1.6,
    acquireRange: 22,
    preferredRange: 15,
    minimumRange: 3,
    attackIntervalMs: 1260,
    attackWindupMs: 260,
    attackAnimMs: 340,
    projectileSpeed: 24,
    collisionRadius: 1.05,
    splashRadius: 3.8,
    attackColor: '#f97316',
    tags: ['aoe', 'burn'],
    summary: '标准地面群伤法师，专门清掉抱团小兵。',
    signature: '群伤、清海、中后排',
  },
  {
    id: 'wolf_rider',
    fallbackName: '狼骑兵',
    shortName: '狼骑',
    icon: '🐺',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'fighter',
    cost: 74,
    cooldownMs: 5800,
    pop: 2,
    maxHp: 570,
    armorHp: 60,
    damage: 82,
    damageType: 'physical',
    moveSpeed: 4.2,
    acquireRange: 12,
    preferredRange: 1.5,
    minimumRange: 0,
    attackIntervalMs: 920,
    attackWindupMs: 120,
    attackAnimMs: 230,
    projectileSpeed: 0,
    collisionRadius: 1.5,
    splashRadius: 0,
    attackColor: '#64748b',
    tags: ['burst', 'flank'],
    summary: '中费冲脸位，会把战团整体往前拱。',
    signature: '快攻、切入、压前',
  },
  {
    id: 'elf_shooter',
    fallbackName: '精灵射手',
    shortName: '精灵',
    icon: '🎯',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'light',
    armorClass: 'light',
    role: 'sniper',
    cost: 78,
    cooldownMs: 5400,
    pop: 2,
    maxHp: 340,
    armorHp: 0,
    damage: 62,
    damageType: 'physical',
    moveSpeed: 1.8,
    acquireRange: 29,
    preferredRange: 22,
    minimumRange: 2.8,
    attackIntervalMs: 760,
    attackWindupMs: 190,
    attackAnimMs: 270,
    projectileSpeed: 34,
    collisionRadius: 0.95,
    splashRadius: 0,
    attackColor: '#10b981',
    tags: ['antiAir', 'focusAir'],
    summary: '长射程对空主力，用来点掉高价值空军。',
    signature: '长射程、专职对空',
  },
  {
    id: 'plague_thrower',
    fallbackName: '瘟疫投手',
    shortName: '瘟投',
    icon: '🧪',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 82,
    cooldownMs: 6000,
    pop: 2,
    maxHp: 340,
    armorHp: 0,
    damage: 56,
    damageType: 'magic',
    moveSpeed: 1.5,
    acquireRange: 21,
    preferredRange: 14,
    minimumRange: 2.6,
    attackIntervalMs: 1180,
    attackWindupMs: 260,
    attackAnimMs: 320,
    projectileSpeed: 21,
    collisionRadius: 1.25,
    splashRadius: 4.1,
    attackColor: '#84cc16',
    tags: ['aoe', 'attrition'],
    summary: '持续消耗型群伤位，适合把敌方地面团压薄。',
    signature: '持续压血、AOE',
  },
  {
    id: 'orc_heavy',
    fallbackName: '兽人重甲兵',
    shortName: '重甲',
    icon: '🪓',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'tank',
    cost: 86,
    cooldownMs: 6800,
    pop: 2,
    maxHp: 980,
    armorHp: 260,
    damage: 48,
    damageType: 'physical',
    moveSpeed: 2.1,
    acquireRange: 11,
    preferredRange: 1.4,
    minimumRange: 0,
    attackIntervalMs: 1360,
    attackWindupMs: 180,
    attackAnimMs: 280,
    projectileSpeed: 0,
    collisionRadius: 1.7,
    splashRadius: 0,
    attackColor: '#475569',
    tags: ['frontline', 'heavy'],
    summary: '真正能顶住团战正面的中坚肉盾。',
    signature: '厚前排、稳推进',
  },
  {
    id: 'ice_witch',
    fallbackName: '冰巫',
    shortName: '冰巫',
    icon: '❄',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 92,
    cooldownMs: 6600,
    pop: 2,
    maxHp: 330,
    armorHp: 0,
    damage: 58,
    damageType: 'magic',
    moveSpeed: 1.5,
    acquireRange: 23,
    preferredRange: 16,
    minimumRange: 2.8,
    attackIntervalMs: 1360,
    attackWindupMs: 250,
    attackAnimMs: 320,
    projectileSpeed: 22,
    collisionRadius: 1,
    splashRadius: 3.4,
    attackColor: '#38bdf8',
    tags: ['aoe', 'slow', 'antiAir'],
    summary: '控速法师，负责把混合团战压慢。',
    signature: '减速、对空、群伤',
  },
  {
    id: 'berserker',
    fallbackName: '狂战士',
    shortName: '狂战',
    icon: '⚒',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'fighter',
    cost: 96,
    cooldownMs: 7200,
    pop: 2,
    maxHp: 760,
    armorHp: 0,
    damage: 108,
    damageType: 'physical',
    moveSpeed: 3.3,
    acquireRange: 11,
    preferredRange: 1.35,
    minimumRange: 0,
    attackIntervalMs: 920,
    attackWindupMs: 120,
    attackAnimMs: 240,
    projectileSpeed: 0,
    collisionRadius: 1.5,
    splashRadius: 0,
    attackColor: '#b45309',
    tags: ['burst', 'heavy'],
    summary: '团战核心切口位，擅长收掉高血重甲。',
    signature: '高攻速、重击',
  },
  {
    id: 'musketeer',
    fallbackName: '火枪佣兵',
    shortName: '火枪',
    icon: '🔫',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'sniper',
    cost: 104,
    cooldownMs: 7500,
    pop: 2,
    maxHp: 380,
    armorHp: 40,
    damage: 96,
    damageType: 'pierce',
    moveSpeed: 1.7,
    acquireRange: 24,
    preferredRange: 18,
    minimumRange: 3.4,
    attackIntervalMs: 1220,
    attackWindupMs: 240,
    attackAnimMs: 300,
    projectileSpeed: 42,
    collisionRadius: 1,
    splashRadius: 0,
    attackColor: '#f59e0b',
    tags: ['pierce', 'antiAir'],
    summary: '高伤点射兵，专门点掉重甲和大体型单位。',
    signature: '重甲杀手、点射',
  },
  {
    id: 'griffin_knight',
    fallbackName: '狮鹫骑士',
    shortName: '狮鹫',
    icon: '🦅',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'air_sup',
    cost: 112,
    cooldownMs: 8500,
    pop: 3,
    maxHp: 920,
    armorHp: 160,
    damage: 74,
    damageType: 'antiAir',
    moveSpeed: 4.1,
    acquireRange: 14,
    preferredRange: 1.5,
    minimumRange: 0,
    attackIntervalMs: 1020,
    attackWindupMs: 130,
    attackAnimMs: 250,
    projectileSpeed: 0,
    collisionRadius: 1.65,
    splashRadius: 0,
    attackColor: '#60a5fa',
    tags: ['antiAir', 'frontline'],
    summary: '空中前排，专门把制空权抢回来。',
    signature: '空战肉搏、压空域',
  },
  {
    id: 'dwarf_ironwall',
    fallbackName: '矮人铁壁',
    shortName: '铁壁',
    icon: '⛏',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'tank',
    cost: 118,
    cooldownMs: 8800,
    pop: 3,
    maxHp: 1120,
    armorHp: 240,
    damage: 58,
    damageType: 'pierce',
    moveSpeed: 2,
    acquireRange: 10,
    preferredRange: 1.4,
    minimumRange: 0,
    attackIntervalMs: 1280,
    attackWindupMs: 180,
    attackAnimMs: 300,
    projectileSpeed: 0,
    collisionRadius: 1.8,
    splashRadius: 0,
    attackColor: '#94a3b8',
    tags: ['frontline', 'pierce', 'heavy'],
    summary: '硬前排兼破甲，适合高压拉扯局。',
    signature: '厚前排、破甲',
  },
  {
    id: 'thunder_mage',
    fallbackName: '雷霆法师',
    shortName: '雷法',
    icon: '⚡',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 126,
    cooldownMs: 9200,
    pop: 3,
    maxHp: 350,
    armorHp: 0,
    damage: 88,
    damageType: 'antiAir',
    moveSpeed: 1.4,
    acquireRange: 24,
    preferredRange: 17,
    minimumRange: 3.2,
    attackIntervalMs: 1450,
    attackWindupMs: 180,
    attackAnimMs: 340,
    projectileSpeed: 26,
    collisionRadius: 1.2,
    splashRadius: 3.8,
    attackColor: '#facc15',
    tags: ['antiAir', 'aoe'],
    summary: '高压对空群伤位，能顺手电掉地面密集团。',
    signature: '雷击、对空、群伤',
  },
  {
    id: 'shadow_assassin',
    fallbackName: '暗影刺客',
    shortName: '刺客',
    icon: '🗡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'fighter',
    cost: 132,
    cooldownMs: 10500,
    pop: 2,
    maxHp: 520,
    armorHp: 0,
    damage: 152,
    damageType: 'pierce',
    moveSpeed: 5.2,
    acquireRange: 12,
    preferredRange: 1.2,
    minimumRange: 0,
    attackIntervalMs: 820,
    attackWindupMs: 100,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 0.9,
    splashRadius: 0,
    attackColor: '#10b981',
    tags: ['burst', 'finisher'],
    summary: '高价切后排位，一旦穿进去就会很疼。',
    signature: '突刺、斩杀、穿插',
  },
  {
    id: 'ballista',
    fallbackName: '弩炮车',
    shortName: '弩炮',
    icon: '🛞',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'structure',
    armorClass: 'structure',
    role: 'siege',
    cost: 148,
    cooldownMs: 11500,
    pop: 4,
    maxHp: 820,
    armorHp: 140,
    damage: 136,
    damageType: 'siege',
    moveSpeed: 1.2,
    acquireRange: 31,
    preferredRange: 25,
    minimumRange: 5.5,
    attackIntervalMs: 1860,
    attackWindupMs: 320,
    attackAnimMs: 380,
    projectileSpeed: 20,
    collisionRadius: 2.2,
    splashRadius: 4.3,
    attackColor: '#fb923c',
    tags: ['siege', 'aoe', 'antiAir'],
    summary: '大体型攻城后排，团战后期压塔能力极强。',
    signature: '攻城、AOE、重投射',
  },
  {
    id: 'young_dragon',
    fallbackName: '幼龙',
    shortName: '幼龙',
    icon: '🐉',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'air_sup',
    cost: 168,
    cooldownMs: 13000,
    pop: 4,
    maxHp: 1180,
    armorHp: 120,
    damage: 128,
    damageType: 'blast',
    moveSpeed: 3.8,
    acquireRange: 20,
    preferredRange: 11,
    minimumRange: 2.2,
    attackIntervalMs: 1380,
    attackWindupMs: 220,
    attackAnimMs: 320,
    projectileSpeed: 22,
    collisionRadius: 2.1,
    splashRadius: 4.5,
    attackColor: '#ef4444',
    tags: ['antiAir', 'aoe', 'finisher'],
    summary: '高费空军压场位，能从上层把战局烧开。',
    signature: '空军核心、AOE',
  },
  {
    id: 'stone_guard',
    fallbackName: '石像卫士',
    shortName: '石卫',
    icon: '🗿',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'large',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'tank',
    cost: 172,
    cooldownMs: 13500,
    pop: 4,
    maxHp: 1480,
    armorHp: 360,
    damage: 66,
    damageType: 'physical',
    moveSpeed: 1.4,
    acquireRange: 10,
    preferredRange: 1.6,
    minimumRange: 0,
    attackIntervalMs: 1520,
    attackWindupMs: 220,
    attackAnimMs: 320,
    projectileSpeed: 0,
    collisionRadius: 2.3,
    splashRadius: 0,
    attackColor: '#94a3b8',
    tags: ['frontline', 'heavy'],
    summary: '大体型堵线墙，专门给后排争取稳定输出时间。',
    signature: '大体型、堵路、稳线',
  },
  {
    id: 'tree_ancient',
    fallbackName: '古树卫',
    shortName: '古树',
    icon: '🌳',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'structure',
    armorClass: 'structure',
    role: 'finisher',
    cost: 205,
    cooldownMs: 16000,
    pop: 5,
    maxHp: 2200,
    armorHp: 320,
    damage: 126,
    damageType: 'siege',
    moveSpeed: 1.2,
    acquireRange: 10,
    preferredRange: 1.8,
    minimumRange: 0,
    attackIntervalMs: 1820,
    attackWindupMs: 260,
    attackAnimMs: 380,
    projectileSpeed: 0,
    collisionRadius: 2.8,
    splashRadius: 3.6,
    attackColor: '#84cc16',
    tags: ['frontline', 'siege', 'aoe', 'finisher'],
    summary: '超重型地面终结兵，会实打实地把路堵死。',
    signature: '巨型、攻城、范围扫击',
  },
  {
    id: 'ogre_lord',
    fallbackName: '食人魔领主',
    shortName: '魔领',
    icon: '👹',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'finisher',
    cost: 228,
    cooldownMs: 17500,
    pop: 5,
    maxHp: 1900,
    armorHp: 280,
    damage: 170,
    damageType: 'pierce',
    moveSpeed: 1.8,
    acquireRange: 11,
    preferredRange: 1.9,
    minimumRange: 0,
    attackIntervalMs: 1660,
    attackWindupMs: 240,
    attackAnimMs: 340,
    projectileSpeed: 0,
    collisionRadius: 2.7,
    splashRadius: 0,
    attackColor: '#f97316',
    tags: ['pierce', 'heavy', 'finisher'],
    summary: '纯粹的大单位点杀者，专门处理重甲和巨型单位。',
    signature: '巨型、重击、斩首',
  },
  {
    id: 'fire_dragon',
    fallbackName: '火龙',
    shortName: '火龙',
    icon: '🐲',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'structure',
    role: 'finisher',
    cost: 248,
    cooldownMs: 19000,
    pop: 6,
    maxHp: 1680,
    armorHp: 180,
    damage: 172,
    damageType: 'blast',
    moveSpeed: 4.3,
    acquireRange: 21,
    preferredRange: 12,
    minimumRange: 3,
    attackIntervalMs: 1520,
    attackWindupMs: 220,
    attackAnimMs: 340,
    projectileSpeed: 24,
    collisionRadius: 3,
    splashRadius: 5.4,
    attackColor: '#ef4444',
    tags: ['antiAir', 'aoe', 'siege', 'finisher'],
    summary: '空地双压的最终收尾兵，能把大团战直接点燃。',
    signature: '终结、AOE、空地双压',
  },
  // 新增地面单位
  {
    id: 'holy_knight',
    fallbackName: '圣骑士',
    shortName: '圣骑',
    icon: '🛡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'tank',
    cost: 105,
    cooldownMs: 8200,
    pop: 3,
    maxHp: 1050,
    armorHp: 280,
    damage: 52,
    damageType: 'magic',
    moveSpeed: 2.2,
    acquireRange: 10,
    preferredRange: 1.4,
    minimumRange: 0,
    attackIntervalMs: 1280,
    attackWindupMs: 180,
    attackAnimMs: 280,
    projectileSpeed: 0,
    collisionRadius: 1.7,
    splashRadius: 0,
    attackColor: '#fbbf24',
    tags: ['frontline', 'heavy', 'heal'],
    summary: '中费前排坦克，兼具魔法伤害和治疗能力。',
    signature: '前排、重甲、治疗',
  },
  {
    id: 'druid',
    fallbackName: '德鲁伊',
    shortName: '德鲁',
    icon: '🌿',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 88,
    cooldownMs: 6200,
    pop: 2,
    maxHp: 320,
    armorHp: 0,
    damage: 50,
    damageType: 'magic',
    moveSpeed: 1.5,
    acquireRange: 18,
    preferredRange: 18,
    minimumRange: 3,
    attackIntervalMs: 1420,
    attackWindupMs: 260,
    attackAnimMs: 340,
    projectileSpeed: 20,
    collisionRadius: 1,
    splashRadius: 3.5,
    attackColor: '#22c55e',
    tags: ['aoe', 'heal', 'support'],
    summary: '支援型法师，提供群体伤害和治疗。',
    signature: '群伤、治疗、支援',
  },
  {
    id: 'siege_ram',
    fallbackName: '攻城锤',
    shortName: '攻城',
    icon: '🔨',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'large',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'structure',
    armorClass: 'structure',
    role: 'siege',
    cost: 135,
    cooldownMs: 10200,
    pop: 3,
    maxHp: 920,
    armorHp: 180,
    damage: 148,
    damageType: 'siege',
    moveSpeed: 1.5,
    acquireRange: 10,
    preferredRange: 1.6,
    minimumRange: 0,
    attackIntervalMs: 1960,
    attackWindupMs: 320,
    attackAnimMs: 380,
    projectileSpeed: 0,
    collisionRadius: 2.2,
    splashRadius: 0,
    attackColor: '#78716c',
    tags: ['siege', 'heavy', 'antiStructure'],
    summary: '重型攻城单位，专门破坏敌方建筑。',
    signature: '攻城、重甲、破建筑',
  },
  {
    id: 'shadow_hunter',
    fallbackName: '暗影猎手',
    shortName: '暗猎',
    icon: '🗡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'fighter',
    cost: 118,
    cooldownMs: 8800,
    pop: 2,
    maxHp: 480,
    armorHp: 0,
    damage: 120,
    damageType: 'pierce',
    moveSpeed: 4.8,
    acquireRange: 12,
    preferredRange: 1.2,
    minimumRange: 0,
    attackIntervalMs: 920,
    attackWindupMs: 100,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 0.9,
    splashRadius: 0,
    attackColor: '#7c3aed',
    tags: ['burst', 'finisher', 'stealth'],
    summary: '高速切入型战士，擅长爆发和收割。',
    signature: '爆发、收割、潜行',
  },
  {
    id: 'elementalist',
    fallbackName: '元素使',
    shortName: '元素',
    icon: '🔮',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 142,
    cooldownMs: 10800,
    pop: 3,
    maxHp: 340,
    armorHp: 0,
    damage: 78,
    damageType: 'magic',
    moveSpeed: 1.4,
    acquireRange: 19,
    preferredRange: 19,
    minimumRange: 3.5,
    attackIntervalMs: 1520,
    attackWindupMs: 280,
    attackAnimMs: 360,
    projectileSpeed: 22,
    collisionRadius: 1.2,
    splashRadius: 4.2,
    attackColor: '#a855f7',
    tags: ['aoe', 'burn', 'elemental'],
    summary: '元素魔法大师，造成大范围元素伤害。',
    signature: '元素、群伤、灼烧',
  },
  {
    id: 'heavy_crossbow',
    fallbackName: '重装弩手',
    shortName: '重弩',
    icon: '🏹',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'sniper',
    cost: 96,
    cooldownMs: 7200,
    pop: 2,
    maxHp: 360,
    armorHp: 60,
    damage: 88,
    damageType: 'pierce',
    moveSpeed: 1.6,
    acquireRange: 26,
    preferredRange: 26,
    minimumRange: 4,
    attackIntervalMs: 1380,
    attackWindupMs: 240,
    attackAnimMs: 300,
    projectileSpeed: 48,
    collisionRadius: 1.5,
    splashRadius: 0,
    attackColor: '#64748b',
    tags: ['pierce', 'antiAir', 'heavy'],
    summary: '重装远程弩手，对空和穿透能力强。',
    signature: '穿透、对空、重装',
  },
  {
    id: 'field_medic',
    fallbackName: '战地医师',
    shortName: '医师',
    icon: '💊',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'caster',
    cost: 68,
    cooldownMs: 5200,
    pop: 2,
    maxHp: 280,
    armorHp: 0,
    damage: 28,
    damageType: 'magic',
    moveSpeed: 1.8,
    acquireRange: 20,
    preferredRange: 20,
    minimumRange: 2,
    attackIntervalMs: 1180,
    attackWindupMs: 200,
    attackAnimMs: 280,
    projectileSpeed: 24,
    collisionRadius: 1,
    splashRadius: 0,
    attackColor: '#34d399',
    tags: ['heal', 'support', 'frontline'],
    summary: '前线治疗支援，维持队伍血线。',
    signature: '治疗、支援、前线',
  },
  {
    id: 'mammoth',
    fallbackName: '猛犸象',
    shortName: '猛犸',
    icon: '🐘',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'structure',
    armorClass: 'structure',
    role: 'tank',
    cost: 185,
    cooldownMs: 14200,
    pop: 4,
    maxHp: 1680,
    armorHp: 320,
    damage: 78,
    damageType: 'physical',
    moveSpeed: 1.1,
    acquireRange: 10,
    preferredRange: 1.8,
    minimumRange: 0,
    attackIntervalMs: 1680,
    attackWindupMs: 260,
    attackAnimMs: 380,
    projectileSpeed: 0,
    collisionRadius: 2.8,
    splashRadius: 3.6,
    attackColor: '#78716c',
    tags: ['frontline', 'heavy', 'aoe'],
    summary: '超重型坦克，群体扫击能力极强。',
    signature: '巨型、重甲、群伤',
  },
  {
    id: 'demolitionist',
    fallbackName: '爆破专家',
    shortName: '爆破',
    icon: '💣',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'siege',
    cost: 158,
    cooldownMs: 11800,
    pop: 3,
    maxHp: 300,
    armorHp: 0,
    damage: 124,
    damageType: 'blast',
    moveSpeed: 1.3,
    acquireRange: 22,
    preferredRange: 22,
    minimumRange: 4,
    attackIntervalMs: 1720,
    attackWindupMs: 300,
    attackAnimMs: 360,
    projectileSpeed: 18,
    collisionRadius: 1.2,
    splashRadius: 5.2,
    attackColor: '#f97316',
    tags: ['siege', 'aoe', 'antiStructure'],
    summary: '爆破专家，大范围破坏敌方建筑。',
    signature: '爆破、群伤、破建筑',
  },
  {
    id: 'blade_master',
    fallbackName: '剑圣',
    shortName: '剑圣',
    icon: '⚔',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorType: 'light',
    armorClass: 'light',
    role: 'finisher',
    cost: 215,
    cooldownMs: 16800,
    pop: 5,
    maxHp: 720,
    armorHp: 0,
    damage: 198,
    damageType: 'pierce',
    moveSpeed: 4.0,
    acquireRange: 11,
    preferredRange: 1.5,
    minimumRange: 0,
    attackIntervalMs: 950,
    attackWindupMs: 100,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 1.5,
    splashRadius: 0,
    attackColor: '#fbbf24',
    tags: ['burst', 'finisher', 'pierce'],
    summary: '终极近战终结者，超高爆发伤害。',
    signature: '终结、爆发、穿透',
  },
  // 新增空军单位
  {
    id: 'wind_spirit',
    fallbackName: '风灵',
    shortName: '风灵',
    icon: '🌪',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'air_only',
    armorType: 'air',
    armorClass: 'swarm',
    role: 'air_sup',
    cost: 78,
    cooldownMs: 5800,
    pop: 2,
    maxHp: 340,
    armorHp: 0,
    damage: 52,
    damageType: 'antiAir',
    moveSpeed: 6.2,
    acquireRange: 14,
    preferredRange: 1.3,
    minimumRange: 0,
    attackIntervalMs: 780,
    attackWindupMs: 120,
    attackAnimMs: 220,
    projectileSpeed: 0,
    collisionRadius: 0.95,
    splashRadius: 0,
    attackColor: '#38bdf8',
    tags: ['antiAir', 'swarm', 'fast'],
    summary: '快速空军骚扰位，专攻敌方空军。',
    signature: '空军、快速、群攻',
  },
  {
    id: 'gargoyle',
    fallbackName: '石像鬼',
    shortName: '石鬼',
    icon: '👹',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'fighter',
    cost: 108,
    cooldownMs: 8200,
    pop: 2,
    maxHp: 680,
    armorHp: 120,
    damage: 72,
    damageType: 'physical',
    moveSpeed: 4.2,
    acquireRange: 14,
    preferredRange: 1.5,
    minimumRange: 0,
    attackIntervalMs: 980,
    attackWindupMs: 130,
    attackAnimMs: 250,
    projectileSpeed: 0,
    collisionRadius: 1.65,
    splashRadius: 0,
    attackColor: '#6b7280',
    tags: ['antiAir', 'heavy', 'frontline'],
    summary: '空中前排战士，兼具防御和攻击。',
    signature: '空军、重甲、前排',
  },
  {
    id: 'phoenix',
    fallbackName: '凤凰',
    shortName: '凤凰',
    icon: '🔥',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'caster',
    cost: 155,
    cooldownMs: 12200,
    pop: 3,
    maxHp: 820,
    armorHp: 80,
    damage: 96,
    damageType: 'blast',
    moveSpeed: 3.6,
    acquireRange: 14,
    preferredRange: 14,
    minimumRange: 2,
    attackIntervalMs: 1280,
    attackWindupMs: 220,
    attackAnimMs: 320,
    projectileSpeed: 20,
    collisionRadius: 2.1,
    splashRadius: 4.8,
    attackColor: '#ef4444',
    tags: ['aoe', 'burn', 'revive'],
    summary: '空中群伤法师，灼烧并可能复活。',
    signature: '空军、群伤、灼烧、复活',
  },
  {
    id: 'thunder_eagle',
    fallbackName: '雷鹰',
    shortName: '雷鹰',
    icon: '🦅',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'sniper',
    cost: 132,
    cooldownMs: 9800,
    pop: 3,
    maxHp: 420,
    armorHp: 40,
    damage: 108,
    damageType: 'antiAir',
    moveSpeed: 4.8,
    acquireRange: 28,
    preferredRange: 28,
    minimumRange: 5,
    attackIntervalMs: 1420,
    attackWindupMs: 240,
    attackAnimMs: 300,
    projectileSpeed: 52,
    collisionRadius: 1.65,
    splashRadius: 0,
    attackColor: '#facc15',
    tags: ['antiAir', 'pierce', 'focus'],
    summary: '远程空中狙击手，专注对空打击。',
    signature: '空军、远程、穿透、专注',
  },
  {
    id: 'angel',
    fallbackName: '天使',
    shortName: '天使',
    icon: '👼',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'single',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'air_sup',
    cost: 175,
    cooldownMs: 13800,
    pop: 4,
    maxHp: 950,
    armorHp: 60,
    damage: 68,
    damageType: 'magic',
    moveSpeed: 3.2,
    acquireRange: 22,
    preferredRange: 22,
    minimumRange: 3,
    attackIntervalMs: 1180,
    attackWindupMs: 200,
    attackAnimMs: 280,
    projectileSpeed: 26,
    collisionRadius: 2.1,
    splashRadius: 0,
    attackColor: '#fbbf24',
    tags: ['heal', 'shield', 'support'],
    summary: '空中支援单位，提供治疗和护盾。',
    signature: '空军、治疗、护盾、支援',
  },
  // Boss 单位
  {
    id: 'shadow_lord',
    fallbackName: '暗影领主',
    shortName: '暗影领主',
    icon: '👑',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'heavy',
    armorClass: 'heavy',
    role: 'tank',
    cost: 999,
    cooldownMs: 999000,
    pop: 10,
    maxHp: 3800,
    armorHp: 450,
    damage: 165,
    damageType: 'magic',
    moveSpeed: 1.2,
    acquireRange: 14,
    preferredRange: 1.5,
    minimumRange: 0,
    attackIntervalMs: 1400,
    attackWindupMs: 200,
    attackAnimMs: 400,
    projectileSpeed: 0,
    collisionRadius: 2.8,
    splashRadius: 3.5,
    attackColor: '#8b5cf6',
    tags: ['boss', 'aoe', 'summon'],
    summary: '第六章 Boss，多阶段隐身与召唤，高 HP 高伤害。',
    signature: 'Boss、召唤、隐身、群伤',
  },
  {
    id: 'storm_dragon',
    fallbackName: '风暴巨龙',
    shortName: '风暴巨龙',
    icon: '🐉',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorType: 'air',
    armorClass: 'heavy',
    role: 'caster',
    cost: 999,
    cooldownMs: 999000,
    pop: 10,
    maxHp: 4200,
    armorHp: 380,
    damage: 185,
    damageType: 'blast',
    moveSpeed: 2.8,
    acquireRange: 22,
    preferredRange: 18,
    minimumRange: 4,
    attackIntervalMs: 1600,
    attackWindupMs: 250,
    attackAnimMs: 450,
    projectileSpeed: 28,
    collisionRadius: 3.0,
    splashRadius: 5.0,
    attackColor: '#3b82f6',
    tags: ['boss', 'aoe', 'air'],
    summary: '第七章 Boss，空军终极挑战，全屏 AOE 与召唤。',
    signature: 'Boss、空军、全屏 AOE、召唤',
  },
];

// 扫描单个单位字段和值域，尽早拦住不完整或不合法的数据。
function validateUnit(unit: FantasyLaneUnitDefinition, seenIds: Set<string>) {
  const errors: string[] = [];

  if (seenIds.has(unit.id)) {
    errors.push(`${unit.id}: 单位 ID 重复`);
  }
  seenIds.add(unit.id);

  REQUIRED_STANDARD_FIELDS.forEach((field) => {
    if (unit[field] === undefined || unit[field] === null) {
      errors.push(`${unit.id}: 缺少标准字段 ${field}`);
    }
  });

  if (!LAYERS.includes(unit.layer)) errors.push(`${unit.id}: 非法 layer=${unit.layer}`);
  if (!RANGE_BANDS.includes(unit.rangeBand)) errors.push(`${unit.id}: 非法 rangeBand=${unit.rangeBand}`);
  if (!FOOTPRINTS.includes(unit.footprint)) errors.push(`${unit.id}: 非法 footprint=${unit.footprint}`);
  if (!ROLES.includes(unit.role)) errors.push(`${unit.id}: 非法 role=${unit.role}`);
  if (!DAMAGE_TYPES.includes(unit.damageType)) errors.push(`${unit.id}: 非法 damageType=${unit.damageType}`);
  if (!DAMAGE_PROFILES.includes(unit.damageProfile)) errors.push(`${unit.id}: 非法 damageProfile=${unit.damageProfile}`);
  if (!TARGET_RULES.includes(unit.targetRule)) errors.push(`${unit.id}: 非法 targetRule=${unit.targetRule}`);
  if (!ARMOR_TYPES.includes(unit.armorType)) errors.push(`${unit.id}: 非法 armorType=${unit.armorType}`);

  if (unit.cost <= 0) errors.push(`${unit.id}: cost 必须大于 0`);
  if (unit.pop <= 0) errors.push(`${unit.id}: pop 必须大于 0`);
  if (unit.maxHp <= 0) errors.push(`${unit.id}: maxHp 必须大于 0`);
  if (unit.damage <= 0) errors.push(`${unit.id}: damage 必须大于 0`);
  if (unit.moveSpeed <= 0) errors.push(`${unit.id}: moveSpeed 必须大于 0`);
  if (unit.attackIntervalMs <= 0) errors.push(`${unit.id}: attackIntervalMs 必须大于 0`);
  if (unit.attackWindupMs < 0) errors.push(`${unit.id}: attackWindupMs 不能小于 0`);
  if (unit.attackAnimMs <= 0) errors.push(`${unit.id}: attackAnimMs 必须大于 0`);
  if (unit.collisionRadius <= 0) errors.push(`${unit.id}: collisionRadius 必须大于 0`);
  if (unit.armorHp < 0) errors.push(`${unit.id}: armorHp 不能小于 0`);
  if (unit.minimumRange < 0) errors.push(`${unit.id}: minimumRange 不能小于 0`);
  if (unit.splashRadius < 0) errors.push(`${unit.id}: splashRadius 不能小于 0`);
  if (unit.acquireRange < unit.preferredRange) errors.push(`${unit.id}: acquireRange 不能小于 preferredRange`);
  if (unit.preferredRange < unit.minimumRange) errors.push(`${unit.id}: preferredRange 不能小于 minimumRange`);
  if (unit.rangeBand === 'melee' && unit.minimumRange !== 0) errors.push(`${unit.id}: 近战单位 minimumRange 必须为 0`);
  if (unit.rangeBand === 'ranged' && unit.minimumRange <= 0) errors.push(`${unit.id}: 远程单位 minimumRange 必须大于 0`);
  if (unit.rangeBand === 'ranged' && unit.projectileSpeed <= 0) errors.push(`${unit.id}: 远程单位 projectileSpeed 必须大于 0`);
  if (unit.rangeBand === 'melee' && unit.projectileSpeed !== 0) errors.push(`${unit.id}: 近战单位 projectileSpeed 必须为 0`);
  if (unit.damageProfile === 'single' && unit.splashRadius !== 0) errors.push(`${unit.id}: single 单位 splashRadius 必须为 0`);
  if (unit.damageProfile === 'aoe' && unit.splashRadius <= 0) errors.push(`${unit.id}: aoe 单位 splashRadius 必须大于 0`);
  if (unit.layer === 'air' && unit.armorType !== 'air') errors.push(`${unit.id}: 空军单位 armorType 必须为 air`);
  if (unit.layer === 'ground' && unit.armorType === 'air') errors.push(`${unit.id}: 地面单位 armorType 不能为 air`);
  if (unit.layer === 'air' && unit.lane !== 'air') errors.push(`${unit.id}: 空军单位 lane 必须稳定映射到 air`);
  if (unit.layer === 'ground' && unit.lane === 'air') errors.push(`${unit.id}: 地面单位 lane 不能映射到 air`);
  if (unit.targetRule === 'air_only' && !unit.canAttackAir) errors.push(`${unit.id}: air_only 单位必须能攻击空军`);
  if (unit.targetRule === 'ground_only' && !unit.canAttackGround) errors.push(`${unit.id}: ground_only 单位必须能攻击地面`);

  return errors;
}

// 对外暴露注册表校验，便于测试线和后续工具直接复用。
export function validateFantasyLaneUnitRegistry(units: FantasyLaneUnitDefinition[]) {
  const seenIds = new Set<string>();
  return units.flatMap((unit) => validateUnit(unit, seenIds));
}

export const FANTASY_LANE_UNITS: FantasyLaneUnitDefinition[] = UNIT_SEEDS.map(createUnit);

export const FANTASY_LANE_HEROES: FantasyLaneHeroDefinition[] = [
  {
    id: 'warlord',
    name: '战帅',
    summary: '偏地面前压与集群推进，能把己方前排整体再往前推一波。',
    passiveSummary: '更适合低费铺场 + 肉盾 + 近战团。',
    skillId: 'iron_march',
    cooldownMs: 32000,
  },
  {
    id: 'archmage',
    name: '大法导师',
    summary: '偏控场和法术，擅长打断敌方密集团推进节奏。',
    passiveSummary: '更适合法师群伤、减速链和中后排清场。',
    skillId: 'meteor_seal',
    cooldownMs: 36000,
  },
  {
    id: 'dragon_rider',
    name: '驭龙者',
    summary: '偏空军与终结兵，能把上空优势转成收尾强压。',
    passiveSummary: '更适合空军、对空和高费终结兵。',
    skillId: 'skybreaker',
    cooldownMs: 42000,
  },
];

export const FANTASY_LANE_TACTICAL_SKILLS: FantasyLaneTacticalSkillDefinition[] = [
  { id: 'fireball', name: '火球', summary: '砸向地面最密集战团，快速削薄一坨兵。', cooldownMs: 18000 },
  { id: 'heal', name: '治疗', summary: '抬基地和前排血线，给团战续住一口气。', cooldownMs: 22000 },
  { id: 'haste', name: '加速', summary: '全线短时提速，让团战压过去。', cooldownMs: 24000 },
  { id: 'freeze', name: '冻结', summary: '让敌方地空推进整体降速，抢回节奏。', cooldownMs: 28000 },
  { id: 'shield', name: '护盾', summary: '给基地和前排补一层临时缓冲。', cooldownMs: 24000 },
];

export const FANTASY_LANE_UNIT_MAP = Object.fromEntries(
  FANTASY_LANE_UNITS.map((unit) => [unit.id, unit]),
) as Record<string, FantasyLaneUnitDefinition>;

export const FANTASY_LANE_HERO_MAP = Object.fromEntries(
  FANTASY_LANE_HEROES.map((hero) => [hero.id, hero]),
) as Record<string, FantasyLaneHeroDefinition>;

export const FANTASY_LANE_TACTICAL_MAP = Object.fromEntries(
  FANTASY_LANE_TACTICAL_SKILLS.map((skill) => [skill.id, skill]),
) as Record<string, FantasyLaneTacticalSkillDefinition>;

export const FANTASY_LANE_UNIT_REGISTRY_ERRORS = validateFantasyLaneUnitRegistry(FANTASY_LANE_UNITS);

if (FANTASY_LANE_UNIT_REGISTRY_ERRORS.length > 0) {
  throw new Error(`fantasy_lane 单位注册表校验失败:\n${FANTASY_LANE_UNIT_REGISTRY_ERRORS.join('\n')}`);
}
