import { UNIT_CONFIGS } from './assets/unitConfigs.ts';
import type {
  FantasyLaneArmorClass,
  FantasyLaneCombatRole,
  FantasyLaneDamageProfile,
  FantasyLaneFootprint,
  FantasyLaneHeroDefinition,
  FantasyLaneLaneId,
  FantasyLaneLayer,
  FantasyLaneRangeBand,
  FantasyLaneRoleGroup,
  FantasyLaneTacticalSkillDefinition,
  FantasyLaneTargetClass,
  FantasyLaneTargetRule,
  FantasyLaneUnitDefinition,
  FantasyLaneUnitSize,
} from './fantasyLaneTypes.ts';

function unitName(id: keyof typeof UNIT_CONFIGS, fallback: string) {
  return UNIT_CONFIGS[id]?.name || fallback;
}

function toLegacyLane(layer: FantasyLaneLayer, role: FantasyLaneCombatRole): FantasyLaneLaneId {
  if (layer === 'air') return 'air';
  if (role === 'tank' || role === 'finisher') return 'front';
  if (role === 'fighter') return 'mid';
  return 'rear';
}

function toLegacyRoleGroup(role: FantasyLaneCombatRole): FantasyLaneRoleGroup {
  switch (role) {
    case 'tank':
      return 'tank';
    case 'fighter':
      return 'melee';
    case 'sniper':
      return 'ranged';
    case 'caster':
      return 'magic';
    case 'air_sup':
      return 'air';
    default:
      return 'finisher';
  }
}

function toLegacySize(footprint: FantasyLaneFootprint): FantasyLaneUnitSize {
  if (footprint === 'small') return 'S';
  if (footprint === 'medium') return 'M';
  if (footprint === 'large') return 'L';
  return 'XL';
}

function toLegacyTargetClass(layer: FantasyLaneLayer, armorClass: FantasyLaneArmorClass): FantasyLaneTargetClass {
  if (layer === 'air') return 'air';
  return armorClass;
}

function createUnit(input: {
  id: keyof typeof UNIT_CONFIGS;
  fallbackName: string;
  shortName: string;
  icon: string;
  layer: FantasyLaneLayer;
  rangeBand: FantasyLaneRangeBand;
  footprint: FantasyLaneFootprint;
  damageProfile: FantasyLaneDamageProfile;
  targetRule: FantasyLaneTargetRule;
  armorClass: FantasyLaneArmorClass;
  role: FantasyLaneCombatRole;
  cost: number;
  cooldownMs: number;
  pop: number;
  maxHp: number;
  armorHp: number;
  damage: number;
  damageType: FantasyLaneUnitDefinition['damageType'];
  moveSpeed: number;
  attackIntervalMs: number;
  preferredRange: number;
  minimumRange: number;
  splashRadius: number;
  collisionRadius: number;
  projectileSpeed: number;
  attackWindupMs: number;
  attackAnimMs: number;
  attackColor: string;
  tags: string[];
  summary: string;
  signature: string;
}): FantasyLaneUnitDefinition {
  const name = unitName(input.id, input.fallbackName);
  const lane = toLegacyLane(input.layer, input.role);
  const roleGroup = toLegacyRoleGroup(input.role);
  const size = toLegacySize(input.footprint);
  const targetClass = toLegacyTargetClass(input.layer, input.armorClass);

  return {
    id: input.id,
    name,
    shortName: input.shortName,
    icon: input.icon,
    layer: input.layer,
    rangeBand: input.rangeBand,
    footprint: input.footprint,
    damageProfile: input.damageProfile,
    targetRule: input.targetRule,
    armorClass: input.armorClass,
    role: input.role,
    pop: input.pop,
    collisionRadius: input.collisionRadius,
    preferredRange: input.preferredRange,
    minimumRange: input.minimumRange,
    projectileSpeed: input.projectileSpeed,
    attackWindupMs: input.attackWindupMs,
    attackAnimMs: input.attackAnimMs,
    attackColor: input.attackColor,
    roleGroup,
    lane,
    cost: input.cost,
    cooldownMs: input.cooldownMs,
    maxHp: input.maxHp,
    armorHp: input.armorHp,
    damage: input.damage,
    damageType: input.damageType,
    targetClass,
    size,
    attackRange: input.preferredRange,
    moveSpeed: input.moveSpeed,
    attackIntervalMs: input.attackIntervalMs,
    splashRadius: input.splashRadius,
    canAttackGround: input.targetRule !== 'air_only',
    canAttackAir: input.targetRule !== 'ground_only',
    tags: input.tags,
    summary: input.summary,
    signature: input.signature,
  };
}

export const FANTASY_LANE_UNITS: FantasyLaneUnitDefinition[] = [
  createUnit({
    id: 'goblin_shield',
    fallbackName: '哥布林盾兵',
    shortName: '盾兵',
    icon: '🛡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'light',
    role: 'tank',
    cost: 35,
    cooldownMs: 3200,
    pop: 1,
    maxHp: 500,
    armorHp: 120,
    damage: 34,
    damageType: 'physical',
    moveSpeed: 2.8,
    attackIntervalMs: 960,
    preferredRange: 1.2,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.2,
    projectileSpeed: 0,
    attackWindupMs: 140,
    attackAnimMs: 240,
    attackColor: '#60a5fa',
    tags: ['frontline', 'starter'],
    summary: '低费开路盾兵，负责把第一波团战站住。',
    signature: '低费、前排、短 CD',
  }),
  createUnit({
    id: 'archer',
    fallbackName: '弓箭手',
    shortName: '弓手',
    icon: '🏹',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorClass: 'light',
    role: 'sniper',
    cost: 42,
    cooldownMs: 3800,
    pop: 1,
    maxHp: 300,
    armorHp: 0,
    damage: 36,
    damageType: 'physical',
    moveSpeed: 1.9,
    attackIntervalMs: 820,
    preferredRange: 19,
    minimumRange: 2.4,
    splashRadius: 0,
    collisionRadius: 1,
    projectileSpeed: 30,
    attackWindupMs: 200,
    attackAnimMs: 280,
    attackColor: '#22c55e',
    tags: ['antiAir', 'starter'],
    summary: '低费后排点射位，补对空和清轻甲都很稳。',
    signature: '低费、对空、持续点射',
  }),
  createUnit({
    id: 'crypt_crawler',
    fallbackName: '墓穴爬兽',
    shortName: '爬兽',
    icon: '🕷',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'swarm',
    role: 'fighter',
    cost: 48,
    cooldownMs: 3400,
    pop: 1,
    maxHp: 430,
    armorHp: 0,
    damage: 62,
    damageType: 'pierce',
    moveSpeed: 4.6,
    attackIntervalMs: 880,
    preferredRange: 1.1,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 0.95,
    projectileSpeed: 0,
    attackWindupMs: 110,
    attackAnimMs: 220,
    attackColor: '#7c3aed',
    tags: ['pierce', 'swarm'],
    summary: '小体型切入兵，能顺着缝隙快速扑到后排。',
    signature: '穿插、破甲、快压',
  }),
  createUnit({
    id: 'bat_swarm',
    fallbackName: '蝠群',
    shortName: '蝠群',
    icon: '🦇',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorClass: 'swarm',
    role: 'air_sup',
    cost: 52,
    cooldownMs: 3600,
    pop: 1,
    maxHp: 360,
    armorHp: 0,
    damage: 58,
    damageType: 'antiAir',
    moveSpeed: 5.1,
    attackIntervalMs: 860,
    preferredRange: 1.3,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 0.95,
    projectileSpeed: 0,
    attackWindupMs: 120,
    attackAnimMs: 220,
    attackColor: '#8b5cf6',
    tags: ['antiAir', 'swarm'],
    summary: '低费空军骚扰位，用来抢空域和拖乱阵型。',
    signature: '空军、短 CD、骚扰',
  }),
  createUnit({
    id: 'flame_warlock',
    fallbackName: '炎术士',
    shortName: '炎术',
    icon: '🔥',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorClass: 'light',
    role: 'caster',
    cost: 72,
    cooldownMs: 5500,
    pop: 2,
    maxHp: 360,
    armorHp: 0,
    damage: 64,
    damageType: 'blast',
    moveSpeed: 1.6,
    attackIntervalMs: 1260,
    preferredRange: 15,
    minimumRange: 3,
    splashRadius: 3.8,
    collisionRadius: 1.05,
    projectileSpeed: 24,
    attackWindupMs: 260,
    attackAnimMs: 340,
    attackColor: '#f97316',
    tags: ['aoe', 'burn'],
    summary: '标准地面群伤法师，专门清掉抱团小兵。',
    signature: '群伤、清海、中后排',
  }),
  createUnit({
    id: 'wolf_rider',
    fallbackName: '狼骑兵',
    shortName: '狼骑',
    icon: '🐺',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'light',
    role: 'fighter',
    cost: 74,
    cooldownMs: 5800,
    pop: 2,
    maxHp: 570,
    armorHp: 60,
    damage: 82,
    damageType: 'physical',
    moveSpeed: 4.2,
    attackIntervalMs: 920,
    preferredRange: 1.5,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.5,
    projectileSpeed: 0,
    attackWindupMs: 120,
    attackAnimMs: 230,
    attackColor: '#64748b',
    tags: ['burst', 'flank'],
    summary: '中费冲脸位，会把战团整体往前拱。',
    signature: '快攻、切入、压前',
  }),
  createUnit({
    id: 'elf_shooter',
    fallbackName: '精灵射手',
    shortName: '精灵',
    icon: '🎯',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorClass: 'light',
    role: 'sniper',
    cost: 78,
    cooldownMs: 5400,
    pop: 2,
    maxHp: 340,
    armorHp: 0,
    damage: 62,
    damageType: 'physical',
    moveSpeed: 1.8,
    attackIntervalMs: 760,
    preferredRange: 22,
    minimumRange: 2.8,
    splashRadius: 0,
    collisionRadius: 0.95,
    projectileSpeed: 34,
    attackWindupMs: 190,
    attackAnimMs: 270,
    attackColor: '#10b981',
    tags: ['antiAir', 'focusAir'],
    summary: '长射程对空主力，用来点掉高价值空军。',
    signature: '长射程、专职对空',
  }),
  createUnit({
    id: 'plague_thrower',
    fallbackName: '瘟疫投手',
    shortName: '瘟投',
    icon: '🧪',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorClass: 'light',
    role: 'caster',
    cost: 82,
    cooldownMs: 6000,
    pop: 2,
    maxHp: 340,
    armorHp: 0,
    damage: 56,
    damageType: 'magic',
    moveSpeed: 1.5,
    attackIntervalMs: 1180,
    preferredRange: 14,
    minimumRange: 2.6,
    splashRadius: 4.1,
    collisionRadius: 1.25,
    projectileSpeed: 21,
    attackWindupMs: 260,
    attackAnimMs: 320,
    attackColor: '#84cc16',
    tags: ['aoe', 'attrition'],
    summary: '持续消耗型群伤位，适合把敌方地面团压薄。',
    signature: '持续压血、AOE',
  }),
  createUnit({
    id: 'orc_heavy',
    fallbackName: '兽人重甲兵',
    shortName: '重甲',
    icon: '🪓',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'heavy',
    role: 'tank',
    cost: 86,
    cooldownMs: 6800,
    pop: 2,
    maxHp: 980,
    armorHp: 260,
    damage: 48,
    damageType: 'physical',
    moveSpeed: 2.1,
    attackIntervalMs: 1360,
    preferredRange: 1.4,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.7,
    projectileSpeed: 0,
    attackWindupMs: 180,
    attackAnimMs: 280,
    attackColor: '#475569',
    tags: ['frontline', 'heavy'],
    summary: '真正能顶住团战正面的中坚肉盾。',
    signature: '厚前排、稳推进',
  }),
  createUnit({
    id: 'ice_witch',
    fallbackName: '冰巫',
    shortName: '冰巫',
    icon: '❄',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorClass: 'light',
    role: 'caster',
    cost: 92,
    cooldownMs: 6600,
    pop: 2,
    maxHp: 330,
    armorHp: 0,
    damage: 42,
    damageType: 'magic',
    moveSpeed: 1.5,
    attackIntervalMs: 1360,
    preferredRange: 16,
    minimumRange: 2.8,
    splashRadius: 3.4,
    collisionRadius: 1,
    projectileSpeed: 22,
    attackWindupMs: 250,
    attackAnimMs: 320,
    attackColor: '#38bdf8',
    tags: ['aoe', 'slow', 'antiAir'],
    summary: '控速法师，负责把混合团战压慢。',
    signature: '减速、对空、群伤',
  }),
  createUnit({
    id: 'berserker',
    fallbackName: '狂战士',
    shortName: '狂战',
    icon: '⚒',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'heavy',
    role: 'fighter',
    cost: 96,
    cooldownMs: 7200,
    pop: 2,
    maxHp: 760,
    armorHp: 0,
    damage: 108,
    damageType: 'physical',
    moveSpeed: 3.3,
    attackIntervalMs: 920,
    preferredRange: 1.35,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.5,
    projectileSpeed: 0,
    attackWindupMs: 120,
    attackAnimMs: 240,
    attackColor: '#b45309',
    tags: ['burst', 'heavy'],
    summary: '团战核心切口位，擅长收掉高血重甲。',
    signature: '高攻速、重击',
  }),
  createUnit({
    id: 'musketeer',
    fallbackName: '火枪佣兵',
    shortName: '火枪',
    icon: '🔫',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'both',
    armorClass: 'heavy',
    role: 'sniper',
    cost: 104,
    cooldownMs: 7500,
    pop: 2,
    maxHp: 380,
    armorHp: 40,
    damage: 96,
    damageType: 'pierce',
    moveSpeed: 1.7,
    attackIntervalMs: 1220,
    preferredRange: 18,
    minimumRange: 3.4,
    splashRadius: 0,
    collisionRadius: 1,
    projectileSpeed: 42,
    attackWindupMs: 240,
    attackAnimMs: 300,
    attackColor: '#f59e0b',
    tags: ['pierce', 'antiAir'],
    summary: '高伤点射兵，专门点掉重甲和大体型单位。',
    signature: '重甲杀手、点射',
  }),
  createUnit({
    id: 'griffin_knight',
    fallbackName: '狮鹫骑士',
    shortName: '狮鹫',
    icon: '🦅',
    layer: 'air',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'both',
    armorClass: 'heavy',
    role: 'air_sup',
    cost: 112,
    cooldownMs: 8500,
    pop: 3,
    maxHp: 920,
    armorHp: 160,
    damage: 74,
    damageType: 'antiAir',
    moveSpeed: 4.1,
    attackIntervalMs: 1020,
    preferredRange: 1.5,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.65,
    projectileSpeed: 0,
    attackWindupMs: 130,
    attackAnimMs: 250,
    attackColor: '#60a5fa',
    tags: ['antiAir', 'frontline'],
    summary: '空中前排，专门把制空权抢回来。',
    signature: '空战肉搏、压空域',
  }),
  createUnit({
    id: 'dwarf_ironwall',
    fallbackName: '矮人铁壁',
    shortName: '铁壁',
    icon: '⛏',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'medium',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'heavy',
    role: 'tank',
    cost: 118,
    cooldownMs: 8800,
    pop: 3,
    maxHp: 1120,
    armorHp: 240,
    damage: 58,
    damageType: 'pierce',
    moveSpeed: 2,
    attackIntervalMs: 1280,
    preferredRange: 1.4,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 1.8,
    projectileSpeed: 0,
    attackWindupMs: 180,
    attackAnimMs: 300,
    attackColor: '#94a3b8',
    tags: ['frontline', 'pierce', 'heavy'],
    summary: '硬前排兼破甲，适合高压拉扯局。',
    signature: '厚前排、破甲',
  }),
  createUnit({
    id: 'thunder_mage',
    fallbackName: '雷霆法师',
    shortName: '雷法',
    icon: '⚡',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'medium',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorClass: 'light',
    role: 'caster',
    cost: 126,
    cooldownMs: 9200,
    pop: 3,
    maxHp: 350,
    armorHp: 0,
    damage: 88,
    damageType: 'antiAir',
    moveSpeed: 1.4,
    attackIntervalMs: 1450,
    preferredRange: 17,
    minimumRange: 3.2,
    splashRadius: 3.8,
    collisionRadius: 1.2,
    projectileSpeed: 26,
    attackWindupMs: 280,
    attackAnimMs: 340,
    attackColor: '#facc15',
    tags: ['antiAir', 'aoe'],
    summary: '高压对空群伤位，能顺手电掉地面密集团。',
    signature: '雷击、对空、群伤',
  }),
  createUnit({
    id: 'shadow_assassin',
    fallbackName: '暗影刺客',
    shortName: '刺客',
    icon: '🗡',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'small',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'light',
    role: 'fighter',
    cost: 132,
    cooldownMs: 10500,
    pop: 2,
    maxHp: 520,
    armorHp: 0,
    damage: 152,
    damageType: 'pierce',
    moveSpeed: 5.2,
    attackIntervalMs: 980,
    preferredRange: 1.2,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 0.9,
    projectileSpeed: 0,
    attackWindupMs: 100,
    attackAnimMs: 220,
    attackColor: '#10b981',
    tags: ['burst', 'finisher'],
    summary: '高价切后排位，一旦穿进去就会很疼。',
    signature: '突刺、斩杀、穿插',
  }),
  createUnit({
    id: 'ballista',
    fallbackName: '弩炮车',
    shortName: '弩炮',
    icon: '🛞',
    layer: 'ground',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorClass: 'structure',
    role: 'siege',
    cost: 148,
    cooldownMs: 11500,
    pop: 4,
    maxHp: 820,
    armorHp: 140,
    damage: 136,
    damageType: 'siege',
    moveSpeed: 1.2,
    attackIntervalMs: 1860,
    preferredRange: 25,
    minimumRange: 5.5,
    splashRadius: 4.3,
    collisionRadius: 2.2,
    projectileSpeed: 20,
    attackWindupMs: 320,
    attackAnimMs: 380,
    attackColor: '#fb923c',
    tags: ['siege', 'aoe', 'antiAir'],
    summary: '大体型攻城后排，团战后期压塔能力极强。',
    signature: '攻城、AOE、重投射',
  }),
  createUnit({
    id: 'young_dragon',
    fallbackName: '幼龙',
    shortName: '幼龙',
    icon: '🐉',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'large',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorClass: 'heavy',
    role: 'air_sup',
    cost: 168,
    cooldownMs: 13000,
    pop: 4,
    maxHp: 1180,
    armorHp: 120,
    damage: 128,
    damageType: 'blast',
    moveSpeed: 3.8,
    attackIntervalMs: 1380,
    preferredRange: 11,
    minimumRange: 2.2,
    splashRadius: 4.5,
    collisionRadius: 2.1,
    projectileSpeed: 22,
    attackWindupMs: 220,
    attackAnimMs: 320,
    attackColor: '#ef4444',
    tags: ['antiAir', 'aoe', 'finisher'],
    summary: '高费空军压场位，能从上层把战局烧开。',
    signature: '空军核心、AOE',
  }),
  createUnit({
    id: 'stone_guard',
    fallbackName: '石像卫士',
    shortName: '石卫',
    icon: '🗿',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'large',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'heavy',
    role: 'tank',
    cost: 172,
    cooldownMs: 13500,
    pop: 4,
    maxHp: 1480,
    armorHp: 360,
    damage: 66,
    damageType: 'physical',
    moveSpeed: 1.4,
    attackIntervalMs: 1520,
    preferredRange: 1.6,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 2.3,
    projectileSpeed: 0,
    attackWindupMs: 220,
    attackAnimMs: 320,
    attackColor: '#94a3b8',
    tags: ['frontline', 'heavy'],
    summary: '大体型堵线墙，专门给后排争取稳定输出时间。',
    signature: '大体型、堵路、稳线',
  }),
  createUnit({
    id: 'tree_ancient',
    fallbackName: '古树卫',
    shortName: '古树',
    icon: '🌳',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'ground_only',
    armorClass: 'structure',
    role: 'finisher',
    cost: 205,
    cooldownMs: 16000,
    pop: 5,
    maxHp: 2200,
    armorHp: 320,
    damage: 126,
    damageType: 'siege',
    moveSpeed: 1.2,
    attackIntervalMs: 1820,
    preferredRange: 1.8,
    minimumRange: 0,
    splashRadius: 3.6,
    collisionRadius: 2.8,
    projectileSpeed: 0,
    attackWindupMs: 260,
    attackAnimMs: 380,
    attackColor: '#84cc16',
    tags: ['frontline', 'siege', 'aoe', 'finisher'],
    summary: '超重型地面终结兵，会实打实地把路堵死。',
    signature: '巨型、攻城、范围扫击',
  }),
  createUnit({
    id: 'ogre_lord',
    fallbackName: '食人魔领主',
    shortName: '魔领',
    icon: '👹',
    layer: 'ground',
    rangeBand: 'melee',
    footprint: 'giant',
    damageProfile: 'single',
    targetRule: 'ground_only',
    armorClass: 'heavy',
    role: 'finisher',
    cost: 228,
    cooldownMs: 17500,
    pop: 5,
    maxHp: 1900,
    armorHp: 280,
    damage: 170,
    damageType: 'pierce',
    moveSpeed: 1.8,
    attackIntervalMs: 1660,
    preferredRange: 1.9,
    minimumRange: 0,
    splashRadius: 0,
    collisionRadius: 2.7,
    projectileSpeed: 0,
    attackWindupMs: 240,
    attackAnimMs: 340,
    attackColor: '#f97316',
    tags: ['pierce', 'heavy', 'finisher'],
    summary: '纯粹的大单位点杀者，专门处理重甲和巨型单位。',
    signature: '巨型、重击、斩首',
  }),
  createUnit({
    id: 'fire_dragon',
    fallbackName: '火龙',
    shortName: '火龙',
    icon: '🐲',
    layer: 'air',
    rangeBand: 'ranged',
    footprint: 'giant',
    damageProfile: 'aoe',
    targetRule: 'both',
    armorClass: 'structure',
    role: 'finisher',
    cost: 248,
    cooldownMs: 19000,
    pop: 6,
    maxHp: 1680,
    armorHp: 180,
    damage: 172,
    damageType: 'blast',
    moveSpeed: 4.3,
    attackIntervalMs: 1520,
    preferredRange: 12,
    minimumRange: 3,
    splashRadius: 5.4,
    collisionRadius: 3,
    projectileSpeed: 24,
    attackWindupMs: 220,
    attackAnimMs: 340,
    attackColor: '#ef4444',
    tags: ['antiAir', 'aoe', 'siege', 'finisher'],
    summary: '空地双压的最终收尾兵，能把大团战直接点燃。',
    signature: '终结、AOE、空地双压',
  }),
];

export const FANTASY_LANE_HEROES: FantasyLaneHeroDefinition[] = [
  {
    id: 'warlord',
    name: '战帅',
    summary: '偏地面前压与集群推进，能把己方前排整体再往前推一波。',
    passiveSummary: '更适合低费铺场 + 肉盾 + 近战团。',
    skillId: 'iron_march',
    cooldownMs: 32000,
  },
  {
    id: 'archmage',
    name: '大法导师',
    summary: '偏控场和法术，擅长打断敌方密集团推进节奏。',
    passiveSummary: '更适合法师群伤、减速链和中后排清场。',
    skillId: 'meteor_seal',
    cooldownMs: 36000,
  },
  {
    id: 'dragon_rider',
    name: '驭龙者',
    summary: '偏空军与终结兵，能把上空优势转成收尾强压。',
    passiveSummary: '更适合空军、对空和高费终结兵。',
    skillId: 'skybreaker',
    cooldownMs: 42000,
  },
];

export const FANTASY_LANE_TACTICAL_SKILLS: FantasyLaneTacticalSkillDefinition[] = [
  { id: 'fireball', name: '火球', summary: '砸向地面最密集战团，快速削薄一坨兵。', cooldownMs: 18000 },
  { id: 'heal', name: '治疗', summary: '抬基地和前排血线，给团战续住一口气。', cooldownMs: 22000 },
  { id: 'haste', name: '加速', summary: '全线短时提速，让团战压过去。', cooldownMs: 24000 },
  { id: 'freeze', name: '冻结', summary: '让敌方地空推进整体降速，抢回节奏。', cooldownMs: 28000 },
  { id: 'shield', name: '护盾', summary: '给基地和前排补一层临时缓冲。', cooldownMs: 24000 },
];

export const FANTASY_LANE_UNIT_MAP = Object.fromEntries(
  FANTASY_LANE_UNITS.map((unit) => [unit.id, unit]),
) as Record<string, FantasyLaneUnitDefinition>;

export const FANTASY_LANE_HERO_MAP = Object.fromEntries(
  FANTASY_LANE_HEROES.map((hero) => [hero.id, hero]),
) as Record<string, FantasyLaneHeroDefinition>;

export const FANTASY_LANE_TACTICAL_MAP = Object.fromEntries(
  FANTASY_LANE_TACTICAL_SKILLS.map((skill) => [skill.id, skill]),
) as Record<string, FantasyLaneTacticalSkillDefinition>;
